service: now-playing

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
    - Effect: Allow
      Action:
        - "sns:*"
      Resource: "arn:aws:sns:us-east-1:*:*"

functions:
  nowPlaying:
    handler: handler.nowPlaying
    events:
      - http:
          path: nowplaying
          method: post
          cors: true
  dispatcher:
    handler: handler.dispatcher
    events:
      - sns: dispatch
  callback:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: get
          cors: true
  authorization:
    handler: handler.authorization
    events:
      - http:
          path: authorization
          method: get

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'users'
